---
title: "Changelog"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{News}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
 
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## [10-06-2025]   
### Référentiels mis à jour  
**Tous champs : **  
`ovalide_ccaminfo` : 2025  
`ovalide_diaginfo` : 2025  
`ovalide_ghminfo_dgf` : 2025  
`ovalide_ghminfo_oqn` : 2025  
`ovalide_racineinfo_dgf` : 2025  
`ovalide_racineinfo_oqn` : 2025  
`open_ccam` : 2025  

## [18-04-2025]   
### Référentiels mis à jour  
**Tous champs : **  
`ccam_pmsi` : V2 2025  
`ccam_pmsi` : passage de la variable ccam_pmsi_classant en variable logique    
`cim` : CIM-10 FR à usage PMSI 2025  
`ucd_ap_ac_cpc` : version mars 2025  
`ucd_en_sus` : version mars 2025  
`ucd_indication` : version mars 2025  
`ucd_libelle` : version mars 2025  

**MCO : **  
`autorisation_mco` : ajout des 4 autorisations (24C, 24D, 25C, 25D) pour les USIP et USIP dérogatoires autorisées dans le cadre de l’octroi des nouvelles autorisations.  
`autorisation_mco` : passage des 3 variables autorisation_mco_rea, autorisation_mco_si et autorisation_mco_sc en variables logiques.  
`ccam_ameli` : V78 du 1er février 2025  
`ccam_icr` : V2 2025  
`cma_mco` : ajout année PMSI 2025  
`dmi_en_sus` : version mars 2025  
`ghs_public` : ajout informations GHS-GHM de la campagne tarifaire publique 2025  
`ghs_prive` : ajout informations GHS-GHM de la campagne tarifaire privée 2025  
`lpp_ameli` : V828 du 15 avril 2025  
`supplements_mco_public` : ajout tarifs publics 2025  
`supplements_mco_prive` : ajout tarifs privés 2025  

**SMR : **  
`cma_smr` : ajout année PMSI 2025  
`csarr_code` : ajout année PMSI 2025  
`csarr_modulateur` : ajout année PMSI 2025 avec le nouveau modulateur L3 "Réalisation dans un autre établissement"  
`gme_public` : ajout informations GMT-GME campagne tarifaire publique 2025  
`gme_prive` : ajout informations GMT-GME campagne tarifaire privée 2025  
`specialites_pharmaceutiques_smr` : version mars 2025  

**PSY : **  
`psy` : mise à jour 2025 du libellé de la Forme d'Activité L13  

### Documentation mise à jour  
Nouvel exemple d'usage de refpmsi : [Actes CSARR de préparations/suivi de dossier dans le nouveau CSAR "1R"](https://denisgustin.github.io/refpmsi/articles/csar.html)  

Nouvel exemple d'usage de refpmsi : [Référentiel des libellés GHM](https://denisgustin.github.io/refpmsi/articles/ghm.html#exemples)


## [10-09-2024]   
### Référentiels mis à jour  
**MCO : **  
`ccam_pmsi` et `ccam_icr` : V4 2024.  
`denombrement_mco_ghs` : données 2023 issues de la base nationale MCO. [source](https://www.atih.sante.fr/sites/default/files/public/content/4807/denombrement_2023.xlsx).  
`denombrement_mco_ghm` : données 2023 issues de la base nationale MCO. [source](https://www.atih.sante.fr/sites/default/files/public/content/4807/denombrement_2023.xlsx).  
`denombrement_mco_diagnostic` : données 2023 issues de la base nationale MCO. [source](https://www.atih.sante.fr/sites/default/files/public/content/4807/denombrement_2023.xlsx).  
`denombrement_mco_ccam` : données 2023 issues de la base nationale MCO. [source](https://www.atih.sante.fr/sites/default/files/public/content/4807/denombrement_2023.xlsx).  

### Nouveaux référentiels `csar_code` et `csar_transcodage`  
En lien avec l'arrivée du nouveau référentiel CSAR qui va prendre le relais à partir de mars 2025 du référentiel CSARR pour le codage de l'activité de RR en SMR.  
[Documentation](https://denisgustin.github.io/refpmsi/articles/csar.html)  

### Nouveaux référentiels `liste_A_mco` et `liste_D_mco`  
La liste des actes CCAM de classification en CMD dans la version 2024 du manuel de groupage MCO (liste dite "en -A").  
La liste des diagnostics CIM de classification en CMD dans la version 2024 du manuel de groupage MCO (liste dite en "-D").  
[Documentation](https://denisgustin.github.io/refpmsi/articles/ghm.html)  


## [05-06-2024]   
### Référentiels mis à jour  
**MCO : **  
`ghs_public` et `ghs_prive` : ajout de l'année PMSI MCO 2024.  
`ovalide_ghminfo_dgf` et `ovalide_ghminfo_oqn` : ajout de l'année PMSI MCO 2024.  
`ghm_intermediaire` et `ghs_monouhcd` : ajout de l'année PMSI MCO 2024.  
`cma_mco` : ajout de l'année PMSI MCO 2024.  
`ghm_regroupement`  et `rghm_regroupement`: année PMSI MCO 2023 avec la version ATIH et projection de l'année 2023 en 2024 en attendant la publication de la version 2024 par l'ATIH.  
`supplements_mco_public` et `supplements_mco_prive`: ajout de l'année PMSI MCO 2024.  
`ccam_pmsi` : V2 2024.  
`ccam_icr` : V2 2024.  
`ccam_ameli` : version 75 du 1er mars 2024.  
`dmi_en_sus` : version avril 2024.  
`lpp_ameli` : version 769 du 12 mars 2024.  
`ucd_en_sus` et `ucd_ap_ac_cpc` : version avril 2024.  
`ucd_indication` : version mars 2024.  
`ucd_libelle` : version février. [source](https://www.atih.sante.fr/sites/default/files/public/content/4710/ref_ucd_2024.xlsx).  

**SMR : **  
`gme_public` : tarifs 2024 actifs à partir du 1er mars 2024 (pour la période Janvier-Février 2024, diviser les tarifs par 1,0307)   
`gme_prive` : tarifs 2024 actifs à partir du 1er mars 2024 (pour la période Janvier-Février 2024, diviser les tarifs par 1,0102)  
`gl` : ajout année 2024 (idem 2023)  
`gr` : ajout année 2024 (idem 2023)  
`gn` : ajout année 2024 (idem 2023)  
`specialites_pharmaceutiques_smr` : version 4 mars 2024  

**PSY : **  
`psy` : ajout des 5 codes type_secteur_dispositif_intersectoriel (G,I,P,Z,D) avec leur libellé.  

### Nouveau référentiel `sous_cmd`  
Pour chaque sous-CMD, son code (01C, 01K, ..), son libellé, le code CMD sous_jacent et le code CMKZ. Référentiel pratique pour rapatrier les libellés de sous-CMD dans un script.  
[Documentation](https://denisgustin.github.io/refpmsi/articles/ghm.html#sous-cmd)  

### Normalisation des intitulés de variables  
Un certain nombre de variables était jusqu'alors nommé avec des parties d'intitulés raccourcis (ex : cim_lib). Toutes ces variables ont été renommées avec des intitulés explicites (ex : cim_libelle).  

Raccourcis concernés et leur normalisation :  
_lib en _libelle  
_niv en _niveau  
_num en _no  
_arbo en _arborescence  
_hier en _hierarchie  
_eval en _evaluation  
_topo en _topographie  

Référentiels concernés :  
`ccam_cma_smr`, `ccam_codification`, `ccam_pmsi`, `ccam_regroupement`, `cim`, `cim_chapitre`, `cim_groupe`, `cim_libelle`, `cm`, `cmd`, `csarr_code`, `csarr_code_note`, `csarr_evaluation`, `csarr_geste_complementaire`, `csarr_hierarchie`, `csarr_hierarchie_note`, `csarr_intervenant`, `dmi_en_sus`, `ghm_regroupement`, `gl`, `gn`, `gr`, `lpp_ameli`, `lpp_ameli_hierarchie`, `rghm_regroupement`, `specialites_pharmaceutiques_smr`, `ucd_en_sus`, `ucd_libelle`

Si vous faîtes appel à `refpmsi::` dans vos scripts, invitation à les relire pour tenir compte de cette normalisation généralisée. En pratique, la plupart du temps, il s'agira de modifier le nom d'une variable (ex : `cim_libelle`au lieu de `cim_lib)`.  

### Référentiels renommés  
Dans la logique de la normalisation des intitulés de variables et pour tenir compte de changement de dénomination du SSR en SMR, renommage de 17 référentiels :  
`ccam_cma_smr` en `ccam_cma_smr`  
`ccam_regroupement_lib` en `ccam_regroupement`  
`ccam_ssr_ponderation` en `ccam_smr_ponderation`  
`cim_lib` en `cim_libelle`  
`cma_ssr` en `cma_smr`  
`csarr_eval` en `csarr_evaluation`  
`csarr_gestcomp` en `csarr_geste_complementaire`  
`csarr_hier` en `csarr_hierarchie`  
`csarr_hier_note` en `csarr_hierarchie_note`  
`csarr_ref` en `csarr_type`  
`ghs_uhcd` en `ghs_monouhcd`  
`lpp_ameli_hier` en `lpp_ameli_hierarchie`  
`spe_pharma_ssr` en `specialites_pharmaceutiques_smr`  
`supp_mco_prive` en `supplements_mco_prive`  
`supp_mco_public` en `supplements_mco_public`  
`ucd_ap_ac` en `ucd_ap_ac_cpc`  
`ucd_lib` en `ucd_libelle`  

### Référentiels supprimés  
Suppression de 6 référentiels de libellés largement redondant avec leurs référentiels liés :   
`dmi_en_sus_lib`, `ghm_lib`, `ghm_regroupement_lib`, `spe_pharma_ssr_lib`, `ucd_ap_ac_lib`, `ucd_en_sus_lib`  

Par exemple, les libellés des regroupements en DA s'obtiennent facilement via ce [mini-script](https://denisgustin.github.io/refpmsi/articles/ghm.html#r%C3%A9f%C3%A9rentiel-des-libell%C3%A9s-des-ga).  

Suppression du référentiel `rgme` qui correspondait aux racines GME de l'ancienne classification GME remplacée en 2022.   

### Autres modifications  
Dans le référentiel `csarr_type`, les 5 variables csarr_dedie, csarr_non_dedie, csarr_collectif, csarr_pluriprofessionnel et csarr_appareillage sont maintenant des variables logiques, plus facilement manipulables.  

Idem dans le référentiel `csarr_evaluation`pour les 4 variables csarr_evaluation_initiale, csarr_evaluation_intermediaire, csarr_evaluation_finale, csarr_evaluation_autres  

### Documentation mise à jour  
`CIM-10 FR à usage PMSI` : mise à jour du code des [exemples](https://denisgustin.github.io/refpmsi/articles/cim.html#exemples).  
`CSARR` : mise à jour du code des [exemples](https://denisgustin.github.io/refpmsi/articles/csarr.html#exemples).  
`GHM` : mise à jour du code des [exemples](https://denisgustin.github.io/refpmsi/articles/ghm.html#exemples) et documentation du nouveau référentiel `sous_cmd`.  
`DMI LPP` : ajout d'un premier exemple de code ["Référentiel de libellé DMI en sus"](https://denisgustin.github.io/refpmsi/articles/dmi_lpp.html#exemples).  
`Spécialités pharmaceutiques SMR` : mise à jour du code des [exemples](https://denisgustin.github.io/refpmsi/articles/specialites_pharmaceutiques_ssr.html#exemples).  


## [31-01-2024]   
### Référentiels mis à jour  
`cim` : mise à jour 2024 avec ajout de la CIM-10 2024  
`gme_public`, `gme_prive` : ajout version 2024 des GME et GMT avec tarifs cibles 2024. Ajout de la variable logique `gmt_7` qui identifie les GMT hebdomadaires associés à un GMT.  
`csarr_code`, `csarr_code_note`, `csarr_ref`,  `csarr_ponderation`, `csarr_incompatibilite_intervenant`, `csarr_hier`, `csarr_hier_note`, `csarr_gestcomp`, `csarr_eval` : mise à jour 2024   
`cma_ssr` : mise à jour 2024   
`ccam_cma_ssr` : mise à jour 2024   
`psy` : mise à jour 2024 des intitulés des lieux d'actes L07, L09, L10 et L12   
`formats_mco` : mise à jour 2024   
`autorisation_mco` : ajout des nouvelles autorisations 2024 en lien avec la réforme des autorisations en soins critiques  

### Nouveaux référentiels  
`csarr_modulateur` : modulateur autorisé par acte CSARR. Référentiel annualisé de 2018 à 2024. [Descriptif](https://denisgustin.github.io/refpmsi/articles/csarr.html#csarr-modulateur)  
`autorisation_smr` : codes et libellés des nouvelles autorisations SMR 2024  

## [21-06-2023]   
### Référentiels mis à jour  
`gme_public`, `gme_prive` : version 2023  
`ovalide_ccaminfo` : version 2023  
`ovalide_diaginfo` : version 2023  
`ovalide_ghminfo_dgf`, `ovalide_ghminfo_oqn` : version 2023  
`ovalide_racineinfo_dgf`, `ovalide_racineinfo_oqn` : version 2023  
`me_ms_mco` : 2023 avec ajout du mode d'entrée O "Pour prélèvement d'organes" et de la provenance V "Avec passage par une structure des urgences d’une autre entité géographique et de celle de l'entité géographique de l'étbalissement"  
`ucd_indication` : 2023 (mai) = libellés des UCD de la base Thésorimed®  

### Nouveau référentiel  
`ucd_lib` : libellés du référentiel UCD de la base de données Thésorimed® ([lien ATIH](https://www.atih.sante.fr/type-de-publication/referentiel)) 

## [11-04-2023]   
### Référentiels mis à jour  
`cim` : version 2023  
Tous les référentiels CSARR (`csarr_code`, `csarr_ponderation`, `csarr_ref`, ...) : version 2023  
`ghs_public`, `ghs_prive` : version 2023  
`supp_mco_public`, `supp_mco_prive` : version 2023  
`ghm_intermediaire`, `ghs_uhcd` : version 2023  
`ccam_pmsi` : v2 2023  
`ccam_icr` : v1 2023  
`lpp_ameli` : v724 (5 avril 2023)  

### Nouveaux référentiels  
`ghm_lib` : libellés uniques des GHM depuis 2018  
`cancerologie_appareil_organe` : codes CIM-10 de localisations tumorales primitives, par appareil et par groupe anatomique (organe)  
`cancerologie_seuil` :  codes CIM-10 des chirurgie cancer  
`lpp_ameli_hier` :  hiérarchie sur 3 arborescences des LPP  

### Evolutions référentiels
`lpp` a été renommé `lpp_ameli`  

### Documentation  
[Nouvel article "DMI-LPP"](https://denisgustin.github.io/refpmsi/articles/dmi_lpp.html)  
[Nouvel article "Cancérologie"](https://denisgustin.github.io/refpmsi/articles/cancerologie.html)  
[Ajout de l'exemple "Comparaison CIM-10 2023 et 2022"](https://denisgustin.github.io/refpmsi/articles/cim.html#comparaison-cim-10-2023-et-2022)  
Ajout de la colonne "Annualisé" dans la [liste des référentiels](https://denisgustin.github.io/refpmsi/articles/liste_ref.html) pour indiquer si le référentiel est annualisé ou non  

## [07-03-2023]   
### Référentiels mis à jour  
`cma_mco` : version 2023 des CMA MCO   
`spe_pharma_ssr` : Version 2 mars 2023 des spécialités pharmaceutiques SSR  

### Nouveaux référentiels  
`ucd_en_sus_lib` : libellés des UCD en sus avec 1 ligne par UCD en sus  
`spe_pharma_ssr_lib` : libellés des spécialités pharmaceutiques SSR avec 1 ligne par spécialité pharmaceutique SSR  
`formats_mco` : descriptif des variables de 5 formats PMSI MCO (RSS groupé, fichier d'information des UM, FICHCOMP LES, FICHCOMP DMI, VID-HOSP)  
`ccam_dm_compatibilite` : liste d'incompatibilité entre acte CCAM et DMI [(source)](https://www.atih.sante.fr/compatibilite-entre-actes-ccam-et-groupes-de-dm)  
`dmi_en_sus` : liste des DMI en sus avec historique des évènements par DMI  
`dmi_en_sus_lib` : libellés des DMI en sus avec 1 libellé par DMI  
`ucd_ap_ac_lib` : libellés des ATU et post-ATU avec 1 libellé par UCD  

### Evolutions référentiels
`spe_pharma_ssr` : historique depuis 2017 et non plus seulement dernière version.  Ajout des 2 variables `date_debut` et `date_fin` de validité  
`ucd_en_sus` : renommage du référentiel `ucd` maintenant supprimé en `ucd_en_sus`. Renommage des variables désormais préfixées `ucd_en_sus_`   
`ucd_ap_ac` : renommage du référentiel `atu` maintenant supprimé en `ucd_ap_ac`. Renommage des variables désormais préfixées `ucd_ap_ac_`   

### Suppression référentiels  
`ucd` : voir ci-dessus le référentiel `ucd_en_sus`  
`atu` : voir ci-dessus le référentiel `ucd_ap_ac`  

### Documentation  
[Descriptif du référentiel `cma_mco`](https://denisgustin.github.io/refpmsi/articles/cim.html#cma-mco)  
[Descriptif du référentiel `cma_ssr`](https://denisgustin.github.io/refpmsi/articles/cim.html#cma-ssr)  
[Ajout de l'exemple d'utilisation "Listes des CMA MCO par niveau - sortie Excel"](https://denisgustin.github.io/refpmsi/articles/cim.html#listes-des-cma-mco-par-niveau---sortie-excel)  
[Descriptif du référentiel `spe_pharma_ss_lib`](https://denisgustin.github.io/refpmsi/articles/specialites_pharmaceutiques_ssr.html#spécialités-pharmaceutiques-ssr-libellés)  
[Descriptif du référentiel `formats_mco`](https://denisgustin.github.io/refpmsi/articles/formats)  

## [28-11-2022]   
### Référentiels mis à jour  
`ccam_pmsi` : V2 2022 de la CCAM à usage PMSI  
`ccam_icr` : V2 2022  
`ccam_ameli` : V69 applicable au 01/04/2022  
`cim` : [version 2022 de CIM-10 FR à usage PMSI](https://denisgustin.github.io/refpmsi/articles/cim.html#cim-10-fr-usage-pmsi) post 04-10-2022 (cf autorisation A49X en DP/DR et code spécial U079 alerte sanitaire)  
`cma_mco` : CMA MCO 2022  
`cma_ssr` : CMA SSR 2022  
`csarr_code`, `csarr_code_note`, `csarr_eval`, `csarr_gestocomp`, `csarr_hier`, `csarr_hier_note`, `csarr_incompatibilite_intervenant`, `csarr_ponderation`, `csarr_ref` : [2022](https://denisgustin.github.io/refpmsi/articles/csarr.html)  
`ghm_regroupement` : [2022](https://denisgustin.github.io/refpmsi/articles/ghm.html#regroupements-ghm-1)  
`ghs_public` et `ghs_prive` : [2022](https://denisgustin.github.io/refpmsi/articles/ghm.html)  
`gme_public` et `gme_prive` : 2022  
`me_ms_mco` : ajout provenance U "Avec passage dans une structure d’accueil des urgences d’une autre entité géographique"  
`me_ms_ssr` : ajout provenance U "Avec passage dans une structure d’accueil des urgences d’une autre entité géographique"  
`ovalide_ccaminfo`, `ovalide_diaginfo`, `ovalide_ghminfo_dgf`, `ovalide_ghminfo_oqn`, `ovalide_racineinfo_dgf`, `ovalide_racineinfo_oqn` : 2022  
`psy` : nouvelles FA 2022 et nouveaux lieux d'acte 2022  
`rghm_regroupement` : [2022](https://denisgustin.github.io/refpmsi/articles/ghm.html#regroupements-des-racines-de-ghm-1)  
`supp_mco_public` et `supp_mco_oqn` : suppléments MCO 2022  

### Nouveau référentiel  
`cim_lib` : libellés de tous les codes CIM-10 depuis 2018 dans leur dernière version  

### Evolutions référentiels
`gme_public` et `gme_prive` : nouvelles variables liées à la version 2022 des GME. [En savoir plus](https://gist.github.com/denisGustin/581e7abf5dd09756008442b0a1b0d01d)  
`cim_polyhandicap` : correction de libellés  
`csarr_ref` : suppression variable csarr_lib (voir csarr_code)  

### Suppression référentiels  
`csarr_extdoc` : voir csarr_code hiérarchie 12.03.01 et 12.03.02  
`csarr_modulateur` : voir csarr_code hiérarchie 12.02  
`ghm_monorum_uhcd_public` et `ghm_monorum_uhcd_prive` : voir nouveau référentiel ghs_uhcd  

## [18-11-2021]  
### Référentiels mis à jour  
csarr_ponderation : [Pondération CSARR V2022 SSR](https://denisgustin.github.io/refpmsi/articles/csarr.html#csarr-pond-rations)
open_ccam : [données de l'année 2020](https://denisgustin.github.io/refpmsi/articles/base_mco.html#open-ccam-1)  
base_mco_diag : [année 2020](https://denisgustin.github.io/refpmsi/articles/base_mco.html)
base_mco_ccam : [année 2020](https://denisgustin.github.io/refpmsi/articles/base_mco.html)

### Nouveaux référentiels  
gl : groupes de lourdeur (GL) de la version 2022 des GME  
gr : groupes de réadaptation (GR) de la version 2022 des GME  

## [08-10-2021]  
### Nouveau référentiel
mco_fg_listes : [Listes D et listes A de groupage MCO dans les CMD](https://denisgustin.github.io/refpmsi/articles/ghm.html#listes-en-d-et-en-a-de-l-algorithme-de-groupage-mco)  

### Evolution référentiel  
cim : nouvelle variable logique cim_precision qui indique si le code CIM-10 a un ou des code(s) fils plus précis ou non. [En savoir plus](https://denisgustin.github.io/refpmsi/articles/cim.html)

## [23-06-2021]  
### Nouveaux référentiels  
ghm_monorum_uhcd_public et ghm_monorum_uhcd_prive : en lien avec la réforme de financement des urgences qui créé, à partir du 1er mars 2021, des GHS dédiés pour chaque racine de GHM, dès que le séjour a lieu uniquement en UHCD et que son mode d'entrée et de sortie est le domicile ([Notice technique ATIH 234-7-2021](https://www.atih.sante.fr/sites/default/files/public/content/4004/notice_technique_n_atih-234-7-2021_nouveautes_financement_2021-hh.pdf)). *Maj 28-11-2022 : référentiels supprimés et remplacés par le référentiel ghs_uhcd*

## [07-06-2021]  
### Référentiels mis à jour  
6 référentiels OVALIDE MCO (ovalide_racineinfo_dgf, ovalide_racineinfo_oqn, ovalide_ghminfo_dgf, ovalide_ghminfo_oqn, ovalide_ccaminfo, ovalide_diaginfo) : année 2021    
ghm_regroupement : [2021](https://denisgustin.github.io/refpmsi/articles/ghm.html#regroupements-ghm-1)
rghm_regroupement : [2021](https://denisgustin.github.io/refpmsi/articles/ghm.html#regroupements-des-racines-de-ghm-1)
csarr_incompatibilite_intervenant : [2021](https://denisgustin.github.io/refpmsi/articles/csarr.html#csarr-incompatibilit-s-intervenants)  

## [24-04-2021]  
### Référentiels mis à jour  
ccam_pmsi : V2 2021 de la CCAM à usage PMSI  
ccam_icr : V2 2021 de la CCAM à usage PMSI  

## [15-04-2021]  
**VERSION STABLE du package**  
Normalisation des noms et des types des variables des référentiels.  

### Nouveaux référentiels  
ghm_intermediaire : 
csarr_hier_note : 
csarr_code_note : 

### Référentiels mis à jour  
cim : 2021  
ccam_pmsi : V1 2021  
ghs_public, ghs_prive: 2022
csarr_code : V2021  

## [12-12-2020]  
### Nouveau référentiel  
anticancereux_intraghs : liste des médicaments anticancéreux non-inscrits sur la liste en sus ou intra-GHS.Expérimentation article 51.  
Version du 9 novembre 2020.  

## [03-08-2020]  
### Nouveau référentiel  
spe_pharma_ssr : spécialités pharmaceutiques SSR version 2017 et version 2020   

## [26-07-2020]  
### Nouveaux référentiels  
5 référentiels issus de dénombrements de la base nationale PMSI SSR 2019  
base_ssr_mp : nombre de séjours ou séances par MMP  
base_ssr_ae : nombre de séjours ou séances par AE  
base_ssr_das : nombre de séjours ou séances par DAS  
base_ssr_csarr : nombre de séjours ou séances par acte CSARR  
base_ssr_ccam : nombre de séjours ou séances par acte CCAM  

3 référentiels issus de dénombrements de la base nationale PMSI MCO 2019  
base_mco_ccam : nombre de séjours ou séances par acte CCAM  
base_mco_diag : nombre de séjours ou séances par diagnostic (DP, DR ou DAS)    
base_mco_ghs : nombre de séjours ou séances par GHS  

open_ccam : par acte CCAM de la base nationale PMSI MCO 2019 (nombre d'actes CCAM, nombre de séjours ou séances, nombre d'actes ambulatoires, nombre de séjours 0 nuit)  

4 référentiels PMSI HAD  
ght_oqn : tarifs GHT OQN (de 2016 à 2020)  
ght_dgf : tarifs GHT DGF (de 2016 à 2020)  
me_ms_had : codes et libellés des modes d'entrée, sortie, provenance et destination en HAD  
had : codes et libellés des natures du séjour, types de lieu de domicile et des modes de prises en charge (MPP, MPA, MPD)  

## [07-05-2020]  
**Mise en ligne du package refpmsi** 
