---
title: "News"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{News}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
 
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## [refpmsi#10] 31 janvier 2024  


### Référentiels mis à jour  

\# `cim` : ajout de la version 2024 de la CIM-10 FR à usage PMSI.  
Version 2024 = version 2023  
\# `gme_public`, `gme_prive` : ajout de la version 2024 des GME et GMT avec les tarifs de la version cible 2024 du nouvel modèle de recettes d’activité.  
Ajout de la variable logique `gmt_7` qui identifie les GMT hebdomadaires associés à un GMT  
\# `csarr_code`, `csarr_code_note`, `csarr_ref`, `csarr_ponderation`, `csarr_incompatibilite_intervenant`, `csarr_hier`, `csarr_hier_note`, `csarr_gestcomp`, `csarr_eval` : ajout de la version 2024.  
Sauf pour le référentiel `csarr_ponderation`, version 2024 = version 2023  
\# `autorisation_mco` : ajout des nouvelles autorisations en lien avec la réforme des autorisations de soins critiques.  
A noter le changement d’intitulé des variables de libellés dans ce référentiel : les suffixes _lib ont été renommés _libelle.  
Exemple : la variable autorisation_mco_lib se nomme maintenant autorisation_mco_libelle  
\# `cma_ssr` : ajout de la liste 2024 des CMA SMR = la liste des CMA SMR 2023  
\# `ccam_cma_ssr` : ajout de la liste 2024 des actes CCAM CMA SMR = la même liste qu’en 2023  
\# `formats_mco` : ajout de la version 2024 des formats des fichiers RSS groupés, FICIUM, FICHCOMP LES, FICHCOMP DMI et VID-HOSP  
\# `psy` : mise à jour des nouveaux libellés 2024 des 4 lieux d’actes L07, L09, L10 et L12.  
Ce référentiel ne conserve que la dernière version (donc dorénavant 2024) des libellés.  

### Nouveau référentiel `csarr_modulateur`  

\# `csarr_modulateur` : par année PMSI, tous les couples (acte CSARR, modulateur autorisé).  
Référentiel annualisé de 2018 à 2024  
[Documentation](https://denisgustin.github.io/refpmsi/articles/csarr.html#csarr-modulateur)  
Source : les fichiers modulateur_csarr_VAAAA.txt (ATIH)  

### Nouveau référentiel `autorisation_smr`  

\# `autorisation_smr` : liste des 13 nouvelles autorisations SMR valables à partir de 2024.  
Pour chacune : code, libellé natif, libellé standardisé et la modalité (qui est la 3eme position du code autorisation)  
[Source](https://www.atih.sante.fr/sites/default/files/public/content/4604/infossmrediteurs2024.pdf)  
On a laissé le référentiel historique `autorisation_ssr` dans le package  

### A venir   

\# Généralisation du renommage des suffixes _lib en _libelle dans les noms de variables  
\# Normalisation + explicite des noms de référentiel. Exemple : `csarr_eval` en `cma_evaluation`  
\# Nouveau référentiel `sous_cmd` : codes et libellés des sous CMD annualisés depuis 2018  
\# Nouveau référentiel `csarr_libelle` : sur le modèle de `cim_lib` (futur `cim_libelle`) avec le dernier intitulé de chaque acte CSARR.  
Utile pour rapatrier uniquement des libellés CSARR dans un script  


## [refpmsi#9]  21 juin 2023  


### Référentiels mis à jour  

\# Les 6 référentiels ovalide MCO (`ovalide_ccaminfo`, `ovalide_diaginfo`, `ovalide_ghminfo_dgf`, `ovalide_ghminfo_oqn`, `ovalide_racineinfo_dgf`, `ovalide_racineinfo_oqn`) dans leur version 2023 suite à la publication par l'ATIH des tables OVALIDE 2023 ([ATIH](https://www.atih.sante.fr/ovalide-mco-2023)).  
On a conservé l'année 2018.  
La variable "dms" dans les 2 référentiels `ovalide_ghminfo_dgf` et `ovalide_ghminfo_oqn` est la durée moyenne de séjour issue de la base nationale pour chaque GHM.  

\# Les 2 référentiels SSR `gme_public` et `gme_prive` dans leur version 2023 avec donc en particulier les tarifs 2023 des GMT  
Ces 2 référentiels comprennent les 13 variables suivantes : gmt, gme, gme_lib, tzf1, gme_cm, gme_gn, gme_gr, gme_gl, gme_niv_severite, gme_niv_readaptation, gme_niv_lourdeur, gmt_8, gmt_type_zf, annee_pmsi, dzf, fzf, tzb, szb, szh, tzf2, tzf3

\# Le référentiel `me_ms_mco`pour ajouter le nouveau mode d'entrée MCO O "Pour prélèvement d'organes" et la nouvelle provenance V "Avec passage par une structure des urgences d’une autre entité géographique et de celle de l'entité géographique de l'établissement"  

\# Le référentiel `ucd_indication` dans sa version de mai 2023 ([ATIH](https://www.atih.sante.fr/unites-communes-de-dispensation-prises-en-charge-en-sus))  

### Nouveau référentiel `ucd_lib`  

Suite à plusieurs demandes, on a rajouté ce nouveau référentiel = les codes UCD 7 et libellés correspondant de la base de données Thésorimed® telle que publiée par l'ATIH   ([ATIH](https://www.atih.sante.fr/type-de-publication/referentiel)).  
Version février 2023  
Exemple d'usage : associer libellés aux codes UCD des ACE H  

## [refpmsi#8] 11 avril 2023  


### Référentiels mis à jour   

\# Les référentiels MCO de la campagne 2023 ( `ghs_public`, `ghs_prive`, `supp_mco_public`, `supp_mco_prive`, `ghm_intermediaire`, `ghs_uhcd` ) dans leur version 2023 suite à la publication par l'ATIH des tarifs GHS de la campagne 2023 ([ATIH](https://www.atih.sante.fr/tarifs-mco-et-had)).  
On a conservé l'année 2018. Ces référentiels comprennent donc les GHS et leurs informations associées de 2018 à 2023 et permettent ainsi de travailler sur les années 2019 à 2023.  

\# Le référentiel `cim`avec la version 2023  
Nous avons publié le code d'un nouveau petit exemple d'usage de ce référentiel : ["Comparaison CIM-10 2023 à 2022"](https://denisgustin.github.io/refpmsi/articles/cim.html#comparaison-cim-10-2023-et-2022)  

\# La CCAM PMSI V2 2023 (`ccam_pmsi`) et la version 1 2023 des ICR (`ccam_icr`)  

\# La LPP V724 du 5 avril 2023 (`lpp_ameli`)  

### Nouveau référentiel `ghm_lib`  

Sur le modèle des référentiels `cim_lib`, `dmi_en_sus_lib`, etc..., nous avons ajouté le référentiel `ghm_lib` qui contient tous les codes GHM dédoublonnés depuis 2018 avec le libellé le plus récent de chacun de ces GHM.  

Un référentiel  pratique pour, par exemple, rapatrier des libellés GHM dans un case-mix sans avoir à ce préoccuper des années PMSI comme dans les référentiels `ghs_public`ou `ghs_prive`.  
[Article](https://denisgustin.github.io/refpmsi/articles/ghm.html#ghm-libell%C3%A9s).  

### 2 nouveaux référentiels de cancérologie  

\# `cancerologie_appareil_organe`: les codes CIM-10 de localisations tumorales primitives, par appareil et par groupe anatomique (organe).  
[Article](https://denisgustin.github.io/refpmsi/articles/cancerologie.html#canc%C3%A9rologie-appareil-et-organe).  
Source : l'algorithme cancer de l'INCa  

\# `cancerologie_seuil` : les codes CIM-10 des chirurgie cancer.  
[Article](https://denisgustin.github.io/refpmsi/articles/cancerologie.html#chirurgie-cancer)  
Source : décret seuil INCa  

### Nouveau référentiel `lpp_ameli_hier`  

Pour regrouper les LPP et DMI en sus en titres, sous-chapitre de niveau 1 et sous-chapitre de niveau 2  
[Article](https://denisgustin.github.io/refpmsi/articles/dmi_lpp.html#lpp-ameli-hi%C3%A9rarchie)  
Source : Open LPP  

### Documentation  

Nouvel [article](https://denisgustin.github.io/refpmsi/articles/dmi_lpp.html) dédié pour les référentiels DMI en sus et les LPP AMELI  

Nouvel [article](https://denisgustin.github.io/refpmsi/articles/cancerologie.html) dédié pour les référentiels de cancérologie  

Dans la [liste des référentiels](https://denisgustin.github.io/refpmsi/articles/liste_ref.html), nous avons ajouté une colonne d'information appelé "Annualisé" qui indique si le référentiel est annualisé au sens PMSI ou pas  

### Divers  

Le référentiel `lpp`a été renommé en `lpp_ameli`  

## [refpmsi#7] 7 mars 2023  


### Nouveau référentiel `dmi_en_sus`  

Référentiel correspondant à la liste des DM pris en charge en sus en MCO, régulièrement mises à jour.  
Source [ATIH](https://www.atih.sante.fr/dispositifs-medicaux-pris-en-charge-en-sus)  

Nous avons retravaillé la variable date d'effet pour la calculer quand elle n'était pas renseignée. Dans dmi_en_sus, 100% des lignes ont donc une date d'effet.

Nous mettrons régulièrement à jour ce référentiel dans l'année, mais pas forcément à chaque mise à jour de la liste.

Voir aussi le nouveau référentiel dmi_en_sus_lib ci-dessous

### Nouveau référentiel `formats_mco`  

Référentiel décrivant chaque variable de 5 fichiers PMSI MCO (RSS groupé, fichier d'information des UM, Fichcomp DMI, Fichcomp LES, VID-HOSP).  
Source [ATIH](https://www.atih.sante.fr/sites/default/files/public/content/4429/formats_mco2023.xlsx)  

Référentiel annualisé de 2018 à 2023.  

Intéressant pour importer proprement dans un data frame ces fichiers textes de production de manière normalisée avec une fonction readr::read_fwf ou vroom::vroom_fwf.  

### Nouveau référentiel `ccam_dm_compatibilite`  

Même si ce référentiel qui établit un lien de cohérence entre acte CCAM et classe de DMI n'a pas été mis à jour, à notre connaissance, par l'ATIH depuis 2014, nous avons pensé intéressant de l'intégrer à refpmsi.  
Source [ATIH](https://www.atih.sante.fr/compatibilite-entre-actes-ccam-et-groupes-de-dm).  

Il comprend 680 lignes avec, pour chaque ligne 4 variables : code acte CCAM, libellé de l'acte (nous avons laissé le libellé natif), groupe de DMI (libellé orginal et libellé normalisé, au sens R, par nos soins).  

Exemple de normalisation : "Implants d’ostéosynthèse" est normalisé en "implants_osteosynthese".  

Utile pour analyser FICHCOMP DMI en lien avec la production d'actes CCAM mais à utiliser avec prudence compte-tenu de sa non mise à jour depuis 2014  

### Autres nouveautés  

\# Mise à jour du référentiel des CMA MCO pour 2023  

\# Mise à jour du référentiel des spécialités pharmaceutiques SSR 2023  

\# Evolution et mise à jour du référentiel ATU qui se nomme désormais ucd_ap_ac  

\# Evolution et mise à jour du référentiel UCD qui se nomme désormais ucd_en_sus  

\# Ajout de 4 référentiels de libellés (`spe_pharma_ssr_lib`, `ucd_en_sus_lib`, `dmi_en_sus_lib`, `ucd_ap_ac_lib`) sur le modèle du référentiel `cim_lib` intégré au package le 28 novembre 2022 : il s'agit de référentiels pratiques pour, essentiellement, récupérer facilement des libellés sans avoir à gérer les référentiels sous-jacents qui peuvent avoir plusieurs lignes pour un même code.  

